### ISSUE TITLE
Server is down... 

### ISSUE THREAD

**Issue by josesimoes** [madskristensen/VsixGallery#14]
Can you please take a look?

**Comment by mikhey** [comment]
I noticed this over the weekend as well and checked this AM to see if it may still be down.  @josesimoes I saw your post and figured I'd post too.  

@madskristensen if there's anything I can do to help, let me know.

**Comment by madskristensen** [comment]
I restarted the server. Thanks for the heads up

**Comment by MagicAndre1981** [comment]
@madskristensen server is down again 

```
HTTP Error 500.37 - ANCM Failed to Start Within Startup Time Limit
Common solutions to this issue:
ANCM failed to start after 120000 milliseconds
```

**Comment by madskristensen** [comment]
Thanks for the heads up @MagicAndre1981. I restarted the server instance

**Comment by MagicAndre1981** [comment]
>  I restarted the server instance

thanks, works now again

**Comment by MagicAndre1981** [comment]
the server is down again @madskristensen 

`The page cannot be displayed because an internal server error has occurred.`
