### ISSUE TITLE
Any chance for a size increase?

### ISSUE THREAD

**Issue by ErikEJ** [madskristensen/VsixGallery#16]
I have a VSIX that is very close to the current upload size limit of 30 MB- any ideas how to support this?

**Comment by madskristensen** [comment]
Did I set that limit or is it asp.net’s default limit?

**Comment by ErikEJ** [comment]
Looks like an ASP.NET Core limit: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#kestrel-maximum-request-body-size

**Comment by ErikEJ** [comment]
And/Or IIS: https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#iis

**Comment by ErikEJ** [comment]
Yikes - now 0.5 MB from the limit (and more bits coming very soon). 50 MB??

[]!(https://media0.giphy.com/media/Q94xQWspTUkShljj8P/source.gif)

**Comment by ErikEJ** [comment]
Any updated or decision - alternatives are using another hosting provider or roll my own...

**Comment by madskristensen** [comment]
Sorry, I forgot all about this. I'm totally fine raising the limit. Thought you were going to send the PR that did it?

**Comment by ErikEJ** [comment]
Where is this hosted? On Windows App Service?

**Comment by ErikEJ** [comment]
Hmm.. Looks like the web.config in src is already configured for 50 MB!?

**Comment by madskristensen** [comment]
Hosted on Azure App Services on Windows

**Comment by ErikEJ** [comment]
I will try to repro and capture the error message.

**Comment by ErikEJ** [comment]
I tested upload of a 31 MB file from my own PC - it worked. Could be an appveyor limitation
