### ISSUE TITLE
Allow extensions directory to be changed

### ISSUE THREAD

**Issue by reduckted** [madskristensen/VsixGallery#18]
I'm looking at deploying this at work, but instead of having the extensions saved under the web root directory, I'd like to have them saved to a completely different directory.

Would you be open to having an option that specifies where to save the extensions to? I'm happy to create a PR for it.

**Comment by madskristensen** [comment]
Absolutely. I've been waiting all these years for someone to deploy this website in their org. PRs are definitely accepted :)

**Comment by reduckted** [comment]
Awesome! There's a few other things that would be nice to have, so expect a few more PRs. 😁

**Comment by madskristensen** [comment]
Keep 'em coming :)
