### ISSUE TITLE
Ability to hide some of the links in the footer

### ISSUE THREAD

**Issue by reduckted** [madskristensen/VsixGallery#24]
Some of the links in the footer may not be useful when running this inside an organization, and could cause a bit of confusion for your users. For example, the "Add your extension" link might not be necessary because there is (hopefully) a standardized approach to publishing extensions using your organization's CI system. Likewise, the "Write your first extension" link might not be useful because you may have your own documentation for creating an extension for your organization.

Having an option to hide some of these links would be useful.

If you're happy with this change, I'll submit a PR. 😄

**Comment by madskristensen** [comment]
GO for it
