### ISSUE TITLE
Require authorization for extension uploads

### ISSUE THREAD

**Issue by reduckted** [madskristensen/VsixGallery#25]
Requiring authorization would be a good way to ensure that extensions are only uploaded by a known entity and helps to enforce your organization's process. 

My use case that is that only the CI system should be able to upload extensions.

The technique that I have in mind is quite simple. A "secret key" is specified in `appsettings.json`. The upload API method would check that the Bearer token in the `Authorization` header matches the secret key (if there's no secret key in appsettings then anyone can upload extensions like they can today). The secret key can be any text you like.

**Comment by madskristensen** [comment]
I love that idea.
