### ISSUE TITLE
2022-04-04 : the server is down 

### ISSUE THREAD

**Issue by MagicAndre1981** [madskristensen/VsixGallery#39]
the server is down again @madskristensen . Can you please check it? 

`The page cannot be displayed because an internal server error has occurred.`

_Originally posted by @MagicAndre1981 in https://github.com/madskristensen/VsixGallery/issues/14#issuecomment-1086947957_

**Comment by MagicAndre1981** [comment]
ok, works fine again.

**Comment by mikhey** [comment]
Looks like the server is down again.

**Comment by MagicAndre1981** [comment]
yes, server is down again:

`The page cannot be displayed because an internal server error has occurred.`

**Comment by MagicAndre1981** [comment]
ok, the issue is fixed, server is online again.
