### ISSUE TITLE
Extension icon not found

### ISSUE THREAD

**Issue by AlonAm** [madskristensen/VsixGallery#47]
Hosting a private instance of the VSIX Gallery on Azure on a Linux machine (app service).
Everything works, including extension upload/publish, except the extension icon is always broken (404 not found).
Using the default configuration with no changes.
Have I missed something in the installation process?

Note, after uploading an extension, in the extension folder within the "extensions" folder, there's only a .json and .vsix files.

**Expected behavior**
The extension icon is presented in the VSIX galley on the extensions list page or extension page.

**Comment by lextm** [comment]
What kind of extensions did you upload? This project only supports VS for Windows extensions, not VS Code extensions.

**Comment by AlonAm** [comment]
Yes, I published a VS extension

**Comment by ErikEJ** [comment]
Duplicate of #44 ?

**Comment by AlonAm** [comment]
No because there are no spaces there.
I also don't see any exceptions in the logs...

**Comment by ErikEJ** [comment]
I doubt that this app was designed to be hosted on a Linux web app.

**Comment by AlonAm** [comment]
Should the icon be present in the directory where the extension was saved? because there's only json and vsix files there

**Comment by AlonAm** [comment]
@ErikEJ I thought about that...I'll give it a try on a Windows machine

**Comment by ErikEJ** [comment]
> should the icon be present in the directory where the extension was saved

yes.

Looks like System.Drawing is used: https://github.com/madskristensen/VsixGallery/blob/master/src/Code/PackageHelper.cs#L119 

I think it does not run well on Linux

**Comment by AlonAm** [comment]
Indeed, I tried using a Windows machine and it works well there.
The gallery runs on .net core 3.1, do you think upgrading will help here?

**Comment by AlonAm** [comment]
Well, after reading [this](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). It seems the only option is upgrade to .net 6 and enable non-windows support (not sure it'll help), or convert the code to use SkiaSharp or Maui libs. I may send a PR later but for now I'll settle for a Windows machine.
Thank you very much for your feedback
