### ISSUE TITLE
Add link to https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VSIXGallery-nightlybuilds

### ISSUE THREAD

**Issue by ErikEJ** [madskristensen/VsixGallery#6]
Maybe add it to this page? https://www.vsixgallery.com/feedguide

**Comment by madskristensen** [comment]
Oh yeah, great idea. In the footer where there are other links or more prominent at the top?

**Comment by ErikEJ** [comment]
At the top - as this is the simple, no-brainer option 😄

**Comment by madskristensen** [comment]
Ok

**Comment by ErikEJ** [comment]
Thanks!
